package utils;

public interface Constants {
    double INITIAL_REGULAR_MOVIE_ABOUT = 2;
    double MAX_REGULAR_RENTAL_PERIOD = 2;
    double EXTRA_AMOUNT_PER_EACH_EXCTRA_REGULAR_MOVIE_DAY = 1.5;

    double INETIAL_CHILDEREN_MOVIE_AMOUT = 1.5;
    double MAX_CHILDEREN_RENTAL_PERIOD = 3;
    double EXTRA_AMOUNT_PER_EACH_EXCTRA_CHILDEREN_MOVIE_DAY = 1.5;

    double AMOUNT_PER_DAY_FOR_NEW_MOVIE = 3;
}
